# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BarrageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import webbrowser

from PyQt5 import QtCore, QtGui, QtWidgets

from api.apiThread import RunThread
from components import Style
from components.Draggable import DraggableWidget, DraggableLabel
import icon
from components.Clickable import ClickableLabel
from components.Avatar import AvatarLabel
from components.ScrollArea import ScrollArea
from components.EffectArea import EffectArea
from panel.BarrageItems import SuperChatItem


class UiBarrageWindow(QtWidgets.QWidget):
    _signal_get_user_detail = QtCore.pyqtSignal(int)
    _signal_update_barrage_visible = QtCore.pyqtSignal(int)

    _signal_live_status_change = QtCore.pyqtSignal(int)
    _signal_live_info_changed = QtCore.pyqtSignal(object)

    def __init__(self):
        super(UiBarrageWindow, self).__init__()
        self.uid = 0
        self.window = None
        self.width_ = 400
        self.height_ = 900
        self.live_link = None
        self.on_top = True
        # get user detail
        self.thread = QtCore.QThread(self)
        self.thread_get_user_detail = RunThread('get_user_detail')
        self.thread_get_user_detail.moveToThread(self.thread)
        self._signal_get_user_detail.connect(self.thread_get_user_detail.run)
        self.thread_get_user_detail.signal.connect(self.call_get_user_detail)
        # message handler
        self.handlers = {
            'MESSAGE': 'add_barrage',
            'DANMU_MSG:4:0:2:2:2:0': 'add_barrage',  # 弹幕信息
            'DANMU_MSG': 'add_barrage',  # 弹幕信息
            'INTERACT_WORD': 'add_join',  # 进场信息
            'SEND_GIFT': 'add_gift',  # 发送礼物
            'COMBO_SEND': 'add_gift',  # 发送礼物
            'WELCOME': 'add_join',  # 欢迎
            # 'SUPER_CHAT_MESSAGE': None,  # SC
            'SUPER_CHAT_MESSAGE_JPN': "add_super_chat",  # SC
            'ENTRY_EFFECT': 'add_join_effect',  # 舰长进场
            'LIVE': 'live_start',  # 直播开始
            'PREPARING': 'live_stop',  # 直播准备/下播
            'ROOM_CHANGE': 'room_change'
        }

        """
        其他常见命令

        'ROOM_BANNER', 
        'ROOM_REAL_TIME_MESSAGE_UPDATE', 
        'NOTICE_MSG', 
        'COMBO_END', 
        'WELCOME_GUARD', 
        'ROOM_RANK', 
        'ACTIVITY_BANNER_UPDATE_V2',
        'PANEL', 
        'USER_TOAST_MSG', 
        'ROOM_BLOCK_MSG', 
        'room_admin_entrance', 
        'ROOM_ADMINS'
        """

    def setupUi(self, window):
        self.window = window
        self.window.closed.connect(self._toggle)
        window.setObjectName("window")
        window.setFixedSize(self.width_, self.height_)
        window.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.Tool | QtCore.Qt.WindowStaysOnTopHint)
        window.setAttribute(QtCore.Qt.WA_TranslucentBackground, True)
        pixMap = QtGui.QPixmap()
        pixMap.loadFromData(QtCore.QByteArray.fromBase64(icon.disconnected))
        window.setWindowIcon(QtGui.QIcon(pixMap))
        window.setWindowTitle('弹幕姬 [未连接]')

        # Window Frame
        self.widget = QtWidgets.QWidget(window)
        self.widget.setGeometry(QtCore.QRect(0, 0, self.width_, 40))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("#widget{background-color: rgba(0,0,0,0.4);}")

        # Drag Handler
        self.drag = DraggableWidget(self.widget)
        self.drag.setGeometry(QtCore.QRect(0, 0, 370, 40))
        self.drag.drag_move.connect(self.drag_move)
        self.drag.drag_end.connect(self.drag_over)
        # Close Button
        self.close_btn = ClickableLabel(self.widget)
        self.close_btn.setGeometry(QtCore.QRect(370, 10, 20, 20))
        self.close_btn.setText('✕')
        self.close_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.close_btn.setCursor(QtCore.Qt.PointingHandCursor)
        self.close_btn.setObjectName('close-btn')
        self.close_btn.setStyleSheet("#close-btn{color:white ;font-size: 16px;}#close-btn:hover{color: #13A4DF}")
        self.close_btn.clicked.connect(self.window.close)
        # Avatar
        self.avatar = AvatarLabel(self.widget)
        self.avatar.setGeometry(QtCore.QRect(2, 2, 36, 36))
        pixMap = QtGui.QPixmap()
        pixMap.loadFromData(QtCore.QByteArray.fromBase64(icon.no_face))
        self.avatar.setup_image(size_=36, img_=pixMap.scaled(36, 36))
        self.avatar.clicked.connect(self.open_url)
        self.avatar.setCursor(QtCore.Qt.PointingHandCursor)
        # Status
        self.status = QtWidgets.QLabel(self.widget)
        self.status.setGeometry(QtCore.QRect(40, 13, 14, 14))
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName('status')
        self.status.setText('●')
        self.status.setStyleSheet("color: red")
        # Title
        self.title = DraggableLabel(self.widget)
        self.title.drag_move.connect(self.drag_move)
        self.title.drag_end.connect(self.drag_over)
        self.title.setGeometry(QtCore.QRect(50, 5, 160, 30))
        self.title.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.title.setObjectName('title')
        self.title.setStyleSheet("#title{font-size: 12px; color: white;font-weight: bold; padding-left: 5px}")
        # Pop
        self.popular_icon = AvatarLabel(self.widget)
        self.popular_icon.setGeometry(QtCore.QRect(274, 12, 16, 16))
        pixMap = QtGui.QPixmap()
        pixMap.loadFromData(QtCore.QByteArray.fromBase64(icon.hot))
        self.popular_icon.setup_image(16, pixMap.scaled(16, 16))
        self.pop = QtWidgets.QLabel(self.widget)
        self.pop.setGeometry(QtCore.QRect(285, 5, 60, 30))
        self.pop.setObjectName('pop')
        self.pop.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.pop.setStyleSheet('#pop{font-size:12px; color: white; padding: 5px 0px;font-family: "微软雅黑", sans-serif;}')
        self.pop.setToolTip("人气")
        self.pop.setText("0")
        # On Top
        self.top = AvatarLabel(self.widget)
        self.top.setGeometry(QtCore.QRect(345, 10, 20, 20))
        pixMap = QtGui.QPixmap()
        pixMap.loadFromData(QtCore.QByteArray.fromBase64(icon.top))
        self.top.setup_image(20, pixMap.scaled(20, 20))
        self.top.clicked.connect(self.toggle_top)
        self.top.setCursor(QtCore.Qt.PointingHandCursor)

        self.effect_widget = EffectArea(window)
        self.setFixedSize(300, 160)
        self.effect_widget.setGeometry(QtCore.QRect(100, 360, 300, 160))

        self.barrage_area = ScrollArea(window)  # QtWidgets.QScrollArea(window)
        self.barrage_area.setProperties(max_count=100, auto_remove=True,
                                        item_style_sheet='color: white;font-size:12px;'
                                                         'font-family: "微软雅黑", sans-serif;'
                                                         'line-height: 20px;padding: 3px 0px;')
        self.barrage_area.setGeometry(QtCore.QRect(0, 40, 400, 700))
        self.barrage_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.barrage_area.auto_hide = True
        self.barrage_area.setStyleSheet(
            Style.scroll_bar_style('border: 0px;background-color: rgba(0,0,0,0.5);', 'rgba(0,0,0,0)'))
        self.barrage_area.stackUnder(self.effect_widget)

        self.split_ = QtWidgets.QWidget(window)
        self.split_.setGeometry(QtCore.QRect(0, 740, 400, 20))
        self.split_.setObjectName("split")
        self.split_.setStyleSheet("#split{background-color: rgba(0,0,0,0.6);}")

        self.gift_label = ClickableLabel(self.split_)
        self.gift_label.setObjectName('gift-label')
        self.gift_label.setText('<span style="color: white">礼物信息</span>')
        self.gift_label.setStyleSheet('#gift-label{font-family: "微软雅黑", sans-serif;}')
        self.gift_label.clicked.connect(self.show_gift)
        self.gift_label.setCursor(QtCore.Qt.PointingHandCursor)
        self.gift_label.setGeometry(QtCore.QRect(110, 0, 60, 20))
        self.gift_label.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.gift_label.setAlignment(QtCore.Qt.AlignCenter)

        self.join_label = ClickableLabel(self.split_)
        self.join_label.setObjectName('join-label')
        self.join_label.setText('<span style="color: #0ebeff"><u>进场信息</u></span>')
        self.join_label.setStyleSheet('#join-label{font-family: "微软雅黑", sans-serif;}')
        self.join_label.clicked.connect(self.show_join)
        self.join_label.setCursor(QtCore.Qt.PointingHandCursor)
        self.join_label.setGeometry(QtCore.QRect(230, 0, 60, 20))
        self.join_label.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.join_label.setAlignment(QtCore.Qt.AlignCenter)

        self.gift_area = ScrollArea(window)
        self.gift_area.setStyleSheet(
            Style.scroll_bar_style('border: 0px;background-color: rgba(0,0,0,0.5);', 'rgba(0,0,0,0)'))
        self.gift_area.setProperties(max_count=40, auto_remove=True,
                                     item_style_sheet='color: white;font-size:12px;'
                                                      'font-family: "微软雅黑", sans-serif;'
                                                      'line-height: 20px;padding: 3px 0px;')
        self.gift_area.setGeometry(QtCore.QRect(0, 760, 400, 140))
        self.gift_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gift_area.auto_hide = True

        self.join_area = ScrollArea(window)
        self.join_area.setStyleSheet(
            Style.scroll_bar_style('border: 0px;background-color: rgba(0,0,0,0.5);', 'rgba(0,0,0,0)'))
        self.join_area.setProperties(max_count=40, auto_remove=True,
                                     item_style_sheet='color: white;font-size:12px;'
                                                      'font-family: "微软雅黑", sans-serif;'
                                                      'line-height: 20px;padding: 3px 0px;')
        self.join_area.setGeometry(QtCore.QRect(0, 760, 400, 140))
        self.join_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.join_area.auto_hide = True
        self.join_area.hide()

        QtCore.QMetaObject.connectSlotsByName(window)

    # 切换标题和图标
    def toggle_barrage_status(self, status):
        pixMap = QtGui.QPixmap()
        pixMap.loadFromData(QtCore.QByteArray.fromBase64(icon.connected if status == 1 else icon.disconnected))
        self.window.setWindowIcon(QtGui.QIcon(pixMap))
        self.window.setWindowTitle('弹幕姬 [已连接]' if status == 1 else '弹幕姬 [未连接]')

    # 切换显示状态
    def _toggle(self):
        if self.window.isVisible():
            self.window.close()
            self._signal_update_barrage_visible.emit(0)
        else:
            self.window.show()
            self.window.activateWindow()
            self._signal_update_barrage_visible.emit(1)

    # 拖动
    def drag_move(self, x, y):
        self.window.move(x, y)

    def drag_over(self, x, y):
        desktop = QtWidgets.QApplication.desktop()
        width = desktop.width()
        height = desktop.height()
        if x < 0:
            x = 0
        elif x > width - self.width_:
            x = width - self.width_
        if y < 0:
            y = 0
        elif y > height - self.height_:
            y = height - self.height_
        print(x, y)
        # self.window.move()

    # 获取用户详情回调
    def call_get_user_detail(self, obj):
        if obj.get('err', '') == '':
            face = obj.get('face', None)
            self.live_link = obj.get('link')
            if face is None:
                pixMap = QtGui.QPixmap()
                pixMap.loadFromData(QtCore.QByteArray.fromBase64(icon.no_face))
                self.avatar.setup_image(size_=36, img_=pixMap.scaled(36, 36))
            else:
                img = QtGui.QImage.fromData(face)
                avatar = QtGui.QPixmap.fromImage(img)
                self.avatar.setup_image(size_=36,
                                        img_=avatar.scaled(36, 36, transformMode=QtCore.Qt.SmoothTransformation))
            self.avatar.setToolTip(obj.get('uname', ''))

    # 更新直播信息
    def update_live_info(self, obj):
        self.init_all_message()
        title = obj.get('title', '')
        status = obj.get('status', '')
        self.status.setStyleSheet("color: {}".format("#59A869" if status == 1 else "#F0F0F0"))
        uid = obj.get('uid', 0)
        self.uid = uid
        text_ = QtGui.QFontMetrics(self.title.font()).elidedText(title, QtCore.Qt.ElideRight, self.title.width())
        self.title.setText(text_)
        self.title.setToolTip(title)
        if not self.thread.isRunning():
            self.thread.start()
        self._signal_get_user_detail.emit(uid)
        self.toggle_barrage_status(1)

    # 更新直播人气
    def update_heartbeat(self, num_):
        str_ = str(num_)
        if num_ > 10000:
            str_ = str(round(num_ / 10000, 1)) + '万'
        self.pop.setText(str_)
        self.pop.setToolTip(str(num_))

    # 显示礼物面板
    def show_gift(self):
        self.gift_label.setText('<span style="color: white">礼物信息</span>')
        self.join_label.setText('<span style="color: #0ebeff"><u>进场信息</u></span>')
        self.gift_area.show()
        scroll_bar = self.gift_area.verticalScrollBar()
        scroll_bar.setValue(scroll_bar.maximum())
        self.join_area.hide()

    # 显示入场面板
    def show_join(self):
        self.gift_label.setText('<span style="color: #0ebeff"><u>礼物信息</u></span>')
        self.join_label.setText('<span style="color: white">进场信息</span>')
        self.gift_area.hide()
        self.join_area.show()
        scroll_bar = self.join_area.verticalScrollBar()
        scroll_bar.setValue(scroll_bar.maximum())

    # 初始化信息
    def init_all_message(self):
        self.live_link = None
        self.barrage_area.clear_items()
        self.gift_area.clear_items()
        self.join_area.clear_items()

    # 点击头像打开直播间
    def open_url(self):
        if self.live_link:
            webbrowser.open(self.live_link)

    # ws 关闭
    def ws_closed(self):
        self.status.setStyleSheet("color: red")
        self.toggle_barrage_status(0)

    # 切换是否置顶
    def toggle_top(self):
        pixMap = QtGui.QPixmap()
        pixMap.loadFromData(QtCore.QByteArray.fromBase64(icon.on_top if self.on_top else icon.top))
        self.top.setup_image(20, pixMap.scaled(20, 20))
        self.on_top = False if self.on_top else True
        if self.on_top:
            self.window.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.Tool | QtCore.Qt.WindowStaysOnTopHint)
        else:
            self.window.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.window.show()
        self.window.activateWindow()

    # 处理信息
    def handle_message(self, elem):
        name_ = self.handlers.get(elem['cmd'], None)
        if name_:
            method = getattr(self, name_)
            method(elem)
        else:
            try:
                print(elem)
            except UnicodeEncodeError as e:
                pass

    # 进场信息
    def add_join(self, elem):
        uname = elem['data']['uname']
        is_welcome = elem['cmd'] == 'WELCOME'
        message = '{} 用户 <span style="font-weight: bold;color: #ADBCD9">{}</span> 进入直播间'.format(
            '' if not is_welcome else '欢迎', uname)
        self.join_area.add_item(message)

    def add_join_effect(self, elem):
        self.effect_widget.add_item(elem)
        str_ = '<span style="color: white">' + str(elem['data']['copy_writing'])
        message = str_.replace('<%', '</span><span style="font-weight: bold;color: #ffdd61">') \
                      .replace('%>', '</span><span style="color: white">') + '</span>'
        self.join_area.add_item(message)

    # 弹幕信息
    def add_barrage(self, elem: dict):
        if elem.get('info', None):
            uid = elem['info'][2][0]
            uname = elem['info'][2][1]
            message = elem['info'][1]
        else:
            uid = elem['data']['uid']
            uname = elem['data']['uname']
            message = elem['data']['msg']
        is_host = uid == self.uid
        str_ = '' if not is_host else '<span style="color: white;">主 </span>'
        str_ += '<span style="font-weight: bold;color: #ADBCD9">{}: </span><span style="color:white;">'.format(uname)
        self.barrage_area.add_item(str_ + message)

    def add_super_chat(self, elem: dict):
        item = SuperChatItem()
        item.setup_elem(elem)
        self.barrage_area.add_item(item)

    # 礼物信息
    def add_gift(self, elem):
        data = elem['data']
        is_combo = elem['cmd'] == 'COMBO_SEND'
        uid = data['uid']
        uname = data['uname']
        action_ = data['action']
        num_ = data['combo_num'] if is_combo else data['num']
        gift_name = data['gift_name'] if is_combo else data['giftName']
        message = '<span style="font-weight: bold;color: #ADBCD9">{}</span> ' \
                  '{} 了 {} 个 <span style="font-weight: bold;color: #ADBCD9">' \
                  '{}</span>'.format(uname, action_, num_, gift_name)
        self.gift_area.add_item(message)

    def live_start(self, elem):
        self.status.setStyleSheet("color: {}".format("#59A869"))
        self._signal_live_status_change.emit(1)

    def live_stop(self, elem):
        self.status.setStyleSheet("color: {}".format("#F0F0F0"))
        self._signal_live_status_change.emit(0)

    def room_change(self, elem):
        title = elem['data']['title']
        # area_id = elem['data']['area_id']
        text_ = QtGui.QFontMetrics(self.title.font()).elidedText(title, QtCore.Qt.ElideRight, self.title.width())
        self.title.setText(text_)
        self.title.setToolTip(title)
        self._signal_live_info_changed.emit(elem['data'])
