# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from components.Clickable import ClickableLabel
from components.Draggable import DraggableWidget
import components.Style as Style


class UiSettingWindow(QtWidgets.QWidget):
    close_and_refresh = QtCore.pyqtSignal(str, str, str)

    def __init__(self):
        super(UiSettingWindow, self).__init__()
        self.window = None
        self.drag = None

    def _show(self, uid, token, cookie):
        self.uid.setText(uid)
        self.token.setText(token)
        self.cookie.setText(cookie)
        self.window.show()

    def setupUi(self, window):
        self.window = window
        window.setObjectName("window")
        window.setFixedSize(450, 240)
        window.setWindowModality(QtCore.Qt.ApplicationModal)
        window.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.Tool)
        window.setStyleSheet("#window{border-color: black;border-style: solid;border-width: 1px;}")

        # Window Frame
        self.widget = QtWidgets.QWidget(window)
        self.widget.setGeometry(QtCore.QRect(0, 0, 450, 30))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("#widget{background: #633812;}")
        # Drag Handler
        self.drag = DraggableWidget(self.widget)
        self.drag.setGeometry(QtCore.QRect(0, 0, 410, 30))
        self.drag.drag_move.connect(self.drag_move)
        # Title
        self.title = QtWidgets.QLabel(self.drag)
        self.title.setGeometry(QtCore.QRect(5, 0, 100, 30))
        self.title.setAlignment(QtCore.Qt.AlignVCenter)
        self.title.setObjectName("title")
        self.title.setStyleSheet("#title{color:white;font-family: Arial, Helvetica, sans-serif;}")
        self.title.setText("用户信息配置")
        # Close Button
        self.close_btn = QtWidgets.QWidget(self.widget)
        self.close_btn.setGeometry(QtCore.QRect(411, 1, 38, 28))
        self.close_btn.setObjectName("close")
        self.close_btn.setStyleSheet("#close:hover{background: red}")
        self.close_label = ClickableLabel(self.close_btn)
        self.close_label.setText('✕')
        self.close_label.setGeometry(QtCore.QRect(0, 0, 38, 28))
        self.close_label.setObjectName("close-btn")
        self.close_label.setAlignment(QtCore.Qt.AlignCenter)
        self.close_label.setStyleSheet("#close-btn{color:white;font-family: Arial, Helvetica, sans-serif;}")
        self.close_label.clicked.connect(self.close)

        self.widget_1 = QtWidgets.QWidget(window)
        self.widget_1.setGeometry(QtCore.QRect(0, 30, 450, 40))
        self.widget_1.setObjectName("widget_1")
        self.label = QtWidgets.QLabel(self.widget_1)
        self.label.setGeometry(QtCore.QRect(15, 5, 55, 30))
        self.label.setObjectName("label")
        self.label.setText("uid:")
        self.uid = QtWidgets.QLineEdit(self.widget_1)
        self.uid.setGeometry(QtCore.QRect(70, 8, 120, 24))
        self.uid.setObjectName("lineEdit")

        self.widget_2 = QtWidgets.QWidget(window)
        self.widget_2.setGeometry(QtCore.QRect(0, 70, 450, 40))
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(15, 5, 55, 30))
        self.label_2.setObjectName("label_2")
        self.label_2.setText("token:")
        self.token = QtWidgets.QLineEdit(self.widget_2)
        self.token.setGeometry(QtCore.QRect(70, 8, 250, 24))
        self.token.setObjectName("lineEdit_2")

        self.widget_3 = QtWidgets.QWidget(window)
        self.widget_3.setGeometry(QtCore.QRect(0, 110, 450, 80))
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(15, 5, 55, 30))
        self.label_3.setObjectName("label_3")
        self.label_3.setText("cookie:")
        self.cookie = QtWidgets.QTextEdit(self.widget_3)
        self.cookie.setGeometry(QtCore.QRect(70, 8, 365, 64))
        self.cookie.setObjectName("textEdit")
        self.cookie.setAcceptRichText(False)

        self.save_btn = QtWidgets.QPushButton(window)
        self.save_btn.setGeometry(QtCore.QRect(180, 195, 90, 30))
        self.save_btn.setObjectName("save_btn")
        self.save_btn.setText("保存并刷新")
        self.save_btn.setCursor(QtCore.Qt.PointingHandCursor)
        self.save_btn.setStyleSheet(Style.button_style('save_btn'))
        self.save_btn.clicked.connect(self.save_and_refresh)

        QtCore.QMetaObject.connectSlotsByName(window)

    def close(self):
        self.window.close()

    def drag_move(self, x, y):
        self.window.move(x, y)

    def save_and_refresh(self):
        self.close_and_refresh.emit(self.uid.text(), self.token.text(), self.cookie.toPlainText())
        self.close()
